include: package:flutter_lints/flutter.yaml

linter:
  rules:
    directives_ordering: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    prefer_const_constructors: true
    implementation_imports: false
