name: mapapp
description: mapapp
version: 1.0.0+1

publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  sqflite: ^2.3.3+1
  location: ^7.0.0
  google_maps_flutter: ^2.9.0
  get: ^4.6.6
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
